"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import {
  AlertCircle,
  CheckCircle2,
  CreditCard,
  Eye,
  Loader2,
  LockKeyhole,
  Printer,
  RefreshCw,
  Users,
  X,
} from "lucide-react";
import TeacherSidebar from "@/components/TeacherSidebar";
import { apiFetch } from "@/lib/api";

export default function TeacherAdmitCardsPage() {
  const [cards, setCards] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [selectedExamId, setSelectedExamId] = useState("");
  const [preview, setPreview] = useState(false);
  const [previewCards, setPreviewCards] = useState([]);

  const load = useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      setCards(await apiFetch("/teacher/admit-cards"));
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  const exams = useMemo(() => {
    const map = new Map();
    cards.forEach((card) => {
      if (!map.has(card.exam_id)) {
        map.set(card.exam_id, {
          id: card.exam_id,
          name: card.exam_name,
          className: `${card.class}${card.section ? `-${card.section}` : ""}`,
        });
      }
    });
    return [...map.values()];
  }, [cards]);

  useEffect(() => {
    if (!selectedExamId && exams.length) setSelectedExamId(String(exams[0].id));
  }, [exams, selectedExamId]);

  const selectedCards = cards.filter(
    (card) => String(card.exam_id) === selectedExamId,
  );
  const releasedCards = selectedCards.filter((card) => card.published);
  const heldCards = selectedCards.filter((card) => !card.published);

  const openPreview = (nextCards) => {
    setPreviewCards(nextCards);
    setPreview(true);
  };

  return (
    <div className="portal-saffron flex min-h-screen bg-gray-50">
      <TeacherSidebar />
      <main className="min-w-0 flex-1">
        <header className="border-b border-emerald-100 bg-white px-5 py-5 lg:px-8">
          <div className="flex items-center justify-between pl-10 lg:pl-0">
            <div>
              <h1 className="text-xl font-bold text-gray-900">
                Class Admit Cards
              </h1>
              <p className="mt-1 text-sm text-gray-500">
                View and print admit cards generated by admin for your class.
              </p>
            </div>
            <button
              onClick={load}
              className="rounded-lg border border-emerald-200 p-2.5 text-emerald-700"
            >
              <RefreshCw size={17} className={loading ? "animate-spin" : ""} />
            </button>
          </div>
        </header>
        <div className="space-y-5 p-5 lg:p-8">
          {loading ? (
            <div className="flex justify-center py-24">
              <Loader2 className="animate-spin text-emerald-600" />
            </div>
          ) : error ? (
            <div className="rounded-2xl border border-red-200 bg-white px-6 py-16 text-center shadow-sm">
              <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-red-50 text-red-600">
                <AlertCircle size={26} />
              </div>
              <h2 className="mt-4 font-bold text-gray-900">
                Could not load admit cards
              </h2>
              <p className="mx-auto mt-2 max-w-md text-sm text-gray-500">
                {error}
              </p>
              <button
                onClick={load}
                className="mt-5 rounded-lg bg-orange-600 px-4 py-2.5 text-sm font-semibold text-white"
              >
                Try Again
              </button>
            </div>
          ) : exams.length ? (
            <>
              <div className="flex flex-col gap-3 rounded-2xl border border-emerald-100 bg-white p-5 shadow-sm sm:flex-row">
                <select
                  value={selectedExamId}
                  onChange={(event) => setSelectedExamId(event.target.value)}
                  className="flex-1 rounded-lg border border-gray-200 px-3 py-2.5 text-sm"
                >
                  {exams.map((exam) => (
                    <option key={exam.id} value={exam.id}>
                      {exam.name} | {exam.className}
                    </option>
                  ))}
                </select>
                <button
                  onClick={() => openPreview(selectedCards)}
                  className="flex items-center justify-center gap-2 rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white"
                >
                  <Printer size={15} /> Preview / Print All
                </button>
              </div>
              <div className="grid gap-3 sm:grid-cols-3">
                {[
                  ["Total Cards", selectedCards.length, Users, "text-slate-700", "bg-slate-50"],
                  ["Released", releasedCards.length, CheckCircle2, "text-emerald-700", "bg-emerald-50"],
                  ["On Hold", heldCards.length, LockKeyhole, "text-amber-700", "bg-amber-50"],
                ].map(([label, value, Icon, color, background]) => (
                  <div
                    key={label}
                    className="rounded-2xl border border-emerald-100 bg-white p-5 shadow-sm"
                  >
                    <div className={`flex h-10 w-10 items-center justify-center rounded-xl ${background} ${color}`}>
                      <Icon size={19} />
                    </div>
                    <p className="mt-4 text-2xl font-bold text-gray-900">{value}</p>
                    <p className="text-sm text-gray-500">{label}</p>
                  </div>
                ))}
              </div>
              <div className="overflow-hidden rounded-2xl border border-emerald-100 bg-white shadow-sm">
                <div className="border-b border-emerald-100 px-5 py-4">
                  <h2 className="font-bold text-gray-900">Student Admit Cards</h2>
                  <p className="mt-1 text-xs text-gray-500">
                    Held cards can be viewed by the class teacher but are hidden from students.
                  </p>
                </div>
                <div className="overflow-x-auto">
                  <table className="w-full min-w-[700px] text-sm">
                    <thead className="bg-emerald-50/70 text-xs text-gray-600">
                      <tr>
                        {["Roll No.", "Student", "Card Number", "Status", "Action"].map((heading) => (
                          <th key={heading} className="px-5 py-3 text-left">{heading}</th>
                        ))}
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-emerald-50">
                      {selectedCards.map((card) => (
                        <tr key={card.id} className="hover:bg-emerald-50/30">
                          <td className="px-5 py-3 text-gray-500">{card.roll_number}</td>
                          <td className="px-5 py-3 font-semibold text-gray-900">{card.student_name}</td>
                          <td className="px-5 py-3 font-mono text-xs text-gray-600">{card.card_number}</td>
                          <td className="px-5 py-3">
                            <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${
                              card.published
                                ? "bg-emerald-50 text-emerald-700"
                                : "bg-amber-50 text-amber-700"
                            }`}>
                              {card.published ? "Released" : "On Hold"}
                            </span>
                          </td>
                          <td className="px-5 py-3">
                            <button
                              onClick={() => openPreview([card])}
                              className="flex items-center gap-1.5 rounded-lg border border-emerald-200 px-3 py-1.5 text-xs font-semibold text-emerald-700"
                            >
                              <Eye size={13} /> Preview
                            </button>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </>
          ) : (
            <div className="rounded-2xl border border-dashed border-emerald-200 bg-white px-6 py-20 text-center">
              <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-600">
                <CreditCard size={26} />
              </div>
              <h2 className="mt-4 font-bold text-gray-900">No admit cards yet</h2>
              <p className="mx-auto mt-2 max-w-md text-sm text-gray-500">
                Cards will appear here after admin publishes the complete date sheet and generates admit cards for your class.
              </p>
            </div>
          )}
        </div>
      </main>
      {preview && (
        <AdmitCardsPreview
          cards={previewCards}
          onClose={() => setPreview(false)}
        />
      )}
    </div>
  );
}

function AdmitCardsPreview({ cards, onClose }) {
  return (
    <div className="fixed inset-0 z-50 overflow-y-auto bg-black/60 p-4">
      <div className="mx-auto max-w-4xl">
        <div className="print:hidden mb-3 flex justify-end gap-2">
          <button
            onClick={() => window.print()}
            className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white"
          >
            Print All
          </button>
          <button onClick={onClose} className="rounded-lg bg-white p-2">
            <X size={18} />
          </button>
        </div>
        <div id="admit-cards-print" className="space-y-4">
          {cards.map((card) => (
            <article key={card.id} className="bg-white p-6 shadow">
              <header className="border-b pb-4 text-center">
                <h2 className="text-xl font-bold">EduERP College</h2>
                <p>{card.exam_name} Admit Card</p>
              </header>
              <div className="grid grid-cols-2 gap-3 py-4 text-sm">
                <p>Student: <strong>{card.student_name}</strong></p>
                <p>Roll No: <strong>{card.roll_number}</strong></p>
                <p>Class: <strong>{card.class}-{card.section}</strong></p>
                <p>Card No: <strong>{card.card_number}</strong></p>
              </div>
              <table className="w-full text-sm">
                <thead className="bg-emerald-50">
                  <tr>
                    {["Subject", "Date", "Time", "Room"].map((item) => (
                      <th key={item} className="p-2 text-left">{item}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {(card.schedule || []).map((item) => (
                    <tr key={`${item.subject}-${item.exam_date}`}>
                      <td className="p-2">{item.subject}</td>
                      <td className="p-2">{item.exam_date?.slice(0, 10)}</td>
                      <td className="p-2">
                        {item.start_time?.slice(0, 5)}-{item.end_time?.slice(0, 5)}
                      </td>
                      <td className="p-2">{item.room || "-"}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </article>
          ))}
        </div>
      </div>
    </div>
  );
}
